# RoleBinding: Vincula a Role Ã  ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mcp-kubernetes-rolebinding
  namespace: imsilva
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mcp-kubernetes-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: imsilva